In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import torch

In [27]:
import torch

# Number of nodes in the graph
num_nodes = 3

# Number of time steps
num_time_steps = 2

# Temporal edge information (random weights for illustration)
temporal_edge_weights = torch.rand(num_nodes, num_nodes, num_time_steps)

# Print the temporal edge weights tensor
print("Temporal Edge Weights Tensor:")
print(temporal_edge_weights)

print(temporal_edge_weights.shape)

Temporal Edge Weights Tensor:
tensor([[[0.9789, 0.9285],
         [0.0201, 0.6680],
         [0.3809, 0.7005]],

        [[0.0685, 0.8150],
         [0.8682, 0.6755],
         [0.8223, 0.7332]],

        [[0.8020, 0.4355],
         [0.6797, 0.7623],
         [0.0498, 0.9840]]])
torch.Size([3, 3, 2])


In [47]:
import torch
import torch.nn as nn

# Number of nodes in the graph
num_nodes = 5

# Number of time steps
num_time_steps = 3

# Temporal edge information (random weights for illustration)
temporal_edge_weights = torch.rand(num_nodes, num_nodes, num_time_steps)

# Define an embedding layer
embedding_dim = 16
embedding_layer = nn.Embedding(num_nodes, embedding_dim)

# Flatten the temporal edge weights tensor for embedding
flat_temporal_edge_weights = temporal_edge_weights.view(-1, num_nodes)

# Apply the embedding layer
embedded_temporal_edge_weights = embedding_layer(flat_temporal_edge_weights.long())

# Reshape back to the original dimensions
embedded_temporal_edge_weights = embedded_temporal_edge_weights.view(num_nodes, num_nodes, num_time_steps, embedding_dim)
# print("weights")
# print(temporal_edge_weights)

# Print the embedded tensor
print("Embedded Temporal Edge Weights Tensor:")
print(embedded_temporal_edge_weights)

print(embedded_temporal_edge_weights.shape)

Embedded Temporal Edge Weights Tensor:
tensor([[[[-0.5022,  1.3646,  0.0252,  ..., -0.7925, -1.4198,  1.0491],
          [-0.5022,  1.3646,  0.0252,  ..., -0.7925, -1.4198,  1.0491],
          [-0.5022,  1.3646,  0.0252,  ..., -0.7925, -1.4198,  1.0491]],

         [[-0.5022,  1.3646,  0.0252,  ..., -0.7925, -1.4198,  1.0491],
          [-0.5022,  1.3646,  0.0252,  ..., -0.7925, -1.4198,  1.0491],
          [-0.5022,  1.3646,  0.0252,  ..., -0.7925, -1.4198,  1.0491]],

         [[-0.5022,  1.3646,  0.0252,  ..., -0.7925, -1.4198,  1.0491],
          [-0.5022,  1.3646,  0.0252,  ..., -0.7925, -1.4198,  1.0491],
          [-0.5022,  1.3646,  0.0252,  ..., -0.7925, -1.4198,  1.0491]],

         [[-0.5022,  1.3646,  0.0252,  ..., -0.7925, -1.4198,  1.0491],
          [-0.5022,  1.3646,  0.0252,  ..., -0.7925, -1.4198,  1.0491],
          [-0.5022,  1.3646,  0.0252,  ..., -0.7925, -1.4198,  1.0491]],

         [[-0.5022,  1.3646,  0.0252,  ..., -0.7925, -1.4198,  1.0491],
          [-0.502

In [18]:
# Load nodes from a Pandas DataFrame
# Example DataFrame with columns X, Y, Z, Atom_Name, Residue_Name, Residue_ID, Atom_Type, and Timeframe
# Load nodes for all timesteps from a .npy file
filepath = 'continuous_edge.csv'  # Replace with the actual file path
df = pd.read_csv(filepath)
df


Edge_Idx   Node1  Node2  Edge_Dist  Timeframe  Edge_Type
0            0  N199_2  O2_11   9.867029         30          2
1            1  N199_2  O2_11   9.910129         32          2
2            2  N199_2  O2_11   9.833108         45          2
3            3  N199_2  O2_11   9.881741         53          2
4            4  N199_2  O2_11   9.684322         54          2
...        ...     ...    ...        ...        ...        ...
1868      1868  N563_2   O2_6   9.811772         28          2
1869      1869  N563_2   O2_6   9.847707         41          2
1870      1870  N563_2   O2_6   9.869133         42          2
1871      1871  N563_2   O2_6   9.941175         44          2
1872      1872  N563_2   O2_6   9.956993         59          2

[1873 rows x 6 columns]

In [20]:
# Extract 'Node1' and 'Node2' columns
nodes_data = df[['Node1', 'Node2']]

# Initialize the OneHotEncoder
encoder = OneHotEncoder(sparse=False, drop='first')

# Fit and transform 'Node1' and 'Node2'
nodes_encoded = encoder.fit_transform(nodes_data)

# Create new column names for the one-hot encoded features
encoded_columns = encoder.get_feature_names_out(['Node1', 'Node2'])

# Replace the original 'Node1' and 'Node2' columns with the one-hot encoded features
df_encoded = pd.concat([df.drop(['Node1', 'Node2'], axis=1), pd.DataFrame(nodes_encoded, columns=encoded_columns)], axis=1)

# Print the encoded DataFrame
df_encoded


/home/mhanowar/Desktop/GNN_repos_server/Virtual_Environment/graphenv/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Edge_Idx  Edge_Dist  Timeframe  Edge_Type  Node1_N211_2  Node1_N275_2  \
0            0   9.867029         30          2           0.0           0.0   
1            1   9.910129         32          2           0.0           0.0   
2            2   9.833108         45          2           0.0           0.0   
3            3   9.881741         53          2           0.0           0.0   
4            4   9.684322         54          2           0.0           0.0   
...        ...        ...        ...        ...           ...           ...   
1868      1868   9.811772         28          2           0.0           0.0   
1869      1869   9.847707         41          2           0.0           0.0   
1870      1870   9.869133         42          2           0.0           0.0   
1871      1871   9.941175         44          2           0.0           0.0   
1872      1872   9.956993         59          2           0.0           0.0   

      Node1_N331_2  Node1_N343_2  Node1_N375_1  Node1_N375_2  ...  \
0              0.0           0.0           0.0           0.0  ...   
1              0.0           0.0           0.0           0.0  ...   
2              0.0           0.0           0.0           0.0  ...   
3              0.0           0.0           0.0           0.0  ...   
4              0.0           0.0           0.0           0.0  ...   
...            ...           ...           ...           ...  ...   
1868           0.0           0.0           0.0           0.0  ...   
1869           0.0           0.0           0.0           0.0  ...   
1870           0.0           0.0           0.0           0.0  ...   
1871           0.0           0.0           0.0           0.0  ...   
1872           0.0           0.0           0.0           0.0  ...   

      Node1_N507_2  Node1_N519_2  Node1_N551_1  Node1_N563_1  Node1_N563_2  \
0              0.0           0.0           0.0           0.0           0.0   
1              0.0           0.0           0.0           0.0           0.0   
2              0.0           0.0           0.0           0.0           0.0   
3              0.0           0.0           0.0           0.0           0.0   
4              0.0           0.0           0.0           0.0           0.0   
...            ...           ...           ...           ...           ...   
1868           0.0           0.0           0.0           0.0           1.0   
1869           0.0           0.0           0.0           0.0           1.0   
1870           0.0           0.0           0.0           0.0           1.0   
1871           0.0           0.0           0.0           0.0           1.0   
1872           0.0           0.0           0.0           0.0           1.0   

      Node2_O1_11  Node2_O1_6  Node2_O2_10  Node2_O2_11  Node2_O2_6  
0             0.0         0.0          0.0          1.0         0.0  
1             0.0         0.0          0.0          1.0         0.0  
2             0.0         0.0          0.0          1.0         0.0  
3             0.0         0.0          0.0          1.0         0.0  
4             0.0         0.0          0.0          1.0         0.0  
...           ...         ...          ...          ...         ...  
1868          0.0         0.0          0.0          0.0         1.0  
1869          0.0         0.0          0.0          0.0         1.0  
1870          0.0         0.0          0.0          0.0         1.0  
1871          0.0         0.0          0.0          0.0         1.0  
1872          0.0         0.0          0.0          0.0         1.0  

[1873 rows x 26 columns]

In [21]:
# Assuming 'filtered_edge_info' is a DataFrame with 'Edge_Type' column
edge_type = df['Edge_Type'].values.astype(int)

# Edge type features using PyTorch
num_edge_types = len(set(edge_type))
print("Number of Edge Types:", num_edge_types)

# One-hot encode the edge types directly using PyTorch
edge_type_feats = torch.nn.functional.one_hot(torch.from_numpy(edge_type-1), num_classes=num_edge_types)

# Print the one-hot encoded features and their dimensions
print("One-Hot Encoded Features:")
print(edge_type_feats)
print("Feature Dimensions:", edge_type_feats.size(1))


Number of Edge Types: 2
One-Hot Encoded Features:
tensor([[0, 1],
        [0, 1],
        [0, 1],
        ...,
        [0, 1],
        [0, 1],
        [0, 1]])
Feature Dimensions: 2


In [22]:
# import pandas as pd
# import numpy as np

# # Assuming 'df' is your DataFrame
# # Numeric feature scaling
# numeric_features = ['Edge_Dist']
# df[numeric_features] = (df[numeric_features] - df[numeric_features].mean()) / df[numeric_features].std()

# # Adding random noise to numeric features
# numeric_noise = np.random.normal(0, 0.1, size=(len(df), len(numeric_features)))
# df[numeric_features] += np.where(df[numeric_features].applymap(np.isreal), numeric_noise, 0)

# # Label smoothing for categorical features (assuming 'Node1' and 'Node2' are categorical)
# categorical_features = ['Node1', 'Node2']
# df[categorical_features] = df[categorical_features].apply(lambda x: x.apply(lambda y: y + np.random.normal(0, 0.1) if isinstance(y, (int, float)) else y))

# # Flipping labels for the target variable
# df['Edge_Type'] = 1 - df['Edge_Type']

# # Adding random noise to the target variable
# df['Edge_Type'] += np.random.choice([-1, 0, 1], size=len(df))
# df['Edge_Type'] = df['Edge_Type'].clip(0, 1)  # Ensure values are between 0 and 1

# # Print the augmented DataFrame
# print(df)
